[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "datarack"
version = "0.2.5"
description = "Manage data easily and efficiently"

authors = [
    { name = "TrattyGod" }
]

license = { file = "LICENSE" }
readme = "README.md"
readme-content-type = "text/markdown"  

repository = "https://github.com/TrattyGod/DataRack-Python-Library/"
keywords = ["data", "storage", "data-management"]  # Add relevant keywords

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10"
]  

[project.dependencies]
numpy = ">=1.21"
pandas = ">=1.3"

[tool.setuptools.packages.find]
include = ["datarack"]
